# Generated by Django 2.0 on 2018-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='app_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
